using Microsoft.AspNetCore.Mvc;
using Linares_Tarea4.Models;
using System.Collections.Generic;

namespace Linares_Tarea4.Controllers
{
    public class PerrosController : Controller
    {
        public IActionResult Index()
        {
            var perros = new List<Perro>
            {
                new Perro { Nombre = "Affenhuahua", Tamano = "Pequeño", Peso = "12-15 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/09/affenhuahua-dog-breed-full-body.webp" },
                new Perro { Nombre = "Affenpinscher", Tamano = "Pequeño", Peso ="3-5 kg ", Edad =" 12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/09/affenpinscher-dog-breed-full-body.webp" },
                new Perro { Nombre = "Algodón de tulear", Tamano = "Pequeño", Peso =" 4-6 kg", Edad ="14-16 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/coton-de-tulear-dog-breed-full-body.webp" },
                new Perro { Nombre = "Auggie", Tamano = "Pequeño", Peso="9-14 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/auggie-aussie-corgi-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Australiano", Tamano = "Pequeño", Peso ="5-14 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/aussiepom-dog-breed-full-body-side-view-1024x768.webp" },
                new Perro { Nombre = "Basenji", Tamano = "Pequeño", Peso ="10-11 kg", Edad ="13-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/basenji-dog-breed-full-body-1024x768.webp"},
                new Perro { Nombre = "Basset fauve de bretaña", Tamano = "Pequeño", Peso ="12-16 kg", Edad ="12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/basset-fauve-de-bretagne-dog-breed-full-body.webp" },
                new Perro { Nombre = "Beagle", Tamano = "Pequeño", Peso ="9-14 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/beagle-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Beagle de bolsillo", Tamano = "Pequeño", Peso ="3-7 kg", Edad ="10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/pocket-beagle-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Beaglier", Tamano = "Pequeño", Peso ="5-9 kg", Edad ="10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/beaglier-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Bichón frisé", Tamano = "Pequeño", Peso ="5-8 kg", Edad ="14-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bichon-frise-dog-breed-full-body.webp" },
                new Perro { Nombre = "Bichón maltés ", Tamano = "Pequeño", Peso ="4-6 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/maltese-bichon-maltichon-dog-breed-full-body.webp" },
                new Perro { Nombre = "Biewer terrier", Tamano = "Pequeño", Peso ="2-4 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/biewer-terrier-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Boloñesa", Tamano = "Pequeño", Peso ="2,5-4 kg ", Edad ="12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bolognese-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Bolonka zwetna", Tamano = "Pequeño", Peso ="2-5 kg", Edad ="12-16 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bolonka-zwetna-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Boshih", Tamano = "Pequeño", Peso ="5-9 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/boshih-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Bugg", Tamano = "Pequeño", Peso ="7-11 kg", Edad ="10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bugg-dog-breed-full-body.webp" },
                new Perro { Nombre = "Buldog de la riviera", Tamano = "Pequeño", Peso ="9-16 kg", Edad ="10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/riviera-bulldog-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Buldog francés", Tamano = "Pequeño", Peso ="7-13 kg", Edad ="10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/french-bulldog-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Buldog francés atigrado", Tamano = "Pequeño", Peso ="7-13 kg", Edad ="10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/french-bulldog-brindle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Bull terrier miniatura", Tamano = "Pequeño", Peso ="8-13 kg", Edad ="10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/miniature-bull-terrier-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Bullhuahua francés", Tamano = "Pequeño", Peso ="5-14 kg", Edad ="10-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/french-bullhuahua-dog-breed-full-body.webp" },
                new Perro { Nombre = "Caniche", Tamano = "Pequeño", Peso ="1,8-41 kg", Edad ="10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/poodle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Caniche francés", Tamano = "Pequeño", Peso ="3-32 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/french-poodle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Caniche miniatura", Tamano = "Pequeño", Peso ="4,5-8 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/miniature-poodle-caniche-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Caniche toy", Tamano = "Pequeño", Peso ="1,8-2,7 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/toy-poodle-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Cárdigan corgi galés", Tamano = "Pequeño", Peso ="11-17 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cardigan-welsh-corgi-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cav-a-jack", Tamano = "Pequeño", Peso ="6-8 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cav-a-jack-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cavachón", Tamano = "Pequeño", Peso ="7-16 kg", Edad ="10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavachon-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cavalier king charles spaniel", Tamano = "Pequeño", Peso ="6-8 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavalier-king-charles-spaniel-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cavapoo (Cavoodle)", Tamano = "Pequeño", Peso ="4-11 kg", Edad =" 12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavapoo-cavoodle-dog-breed-full-body-side-768x576.webp" },
                new Perro { Nombre = "Cavapoochon", Tamano = "Pequeño", Peso ="5-9 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavapoochon-dog-breed-full-body-side-768x576.jpg" },
                new Perro { Nombre = "Cavoodle", Tamano = "Pequeño", Peso ="4-11 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavapoo-cavoodle-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cesky Terrier", Tamano = "Pequeño", Peso ="6-11 kg ", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/cesky-terrier-czech-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cheagle", Tamano = "Pequeño", Peso ="4-9 kg", Edad ="10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/cheagle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Chi-poo", Tamano = "Pequeño", Peso ="2-9 kg", Edad ="12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/chi-poo-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Chigi", Tamano = "Pequeño", Peso ="5-9 kg", Edad ="12-16 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/chigi-dog-breed-full-body1-768x576.webp" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" },
                new Perro { Nombre = "", Tamano = "", Peso ="", Edad ="", ImagenUrl = "" }

            return View(perros);
        }
    }
}
