using Microsoft.AspNetCore.Mvc;
using Linares_Tarea4.Models;
using System.Collections.Generic;

namespace Linares_Tarea4.Controllers
{
    public class PerrosController : Controller
    {
        public IActionResult Index()
        {
            var perros = new List<Perro>
            {
                new Perro { Nombre = "Affenhuahua", Tamano = "Pequeño", Peso = "12-15 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/09/affenhuahua-dog-breed-full-body.webp" },
                new Perro { Nombre = "Affenpinscher", Tamano = "Pequeño", Peso = "3-5 kg ", Edad = " 12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/09/affenpinscher-dog-breed-full-body.webp" },
                new Perro { Nombre = "Algodón de tulear", Tamano = "Pequeño", Peso = " 4-6 kg", Edad = "14-16 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/coton-de-tulear-dog-breed-full-body.webp" },
                new Perro { Nombre = "Auggie", Tamano = "Pequeño", Peso = "9-14 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/auggie-aussie-corgi-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Australiano", Tamano = "Pequeño", Peso = "5-14 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/aussiepom-dog-breed-full-body-side-view-1024x768.webp" },
                new Perro { Nombre = "Basenji", Tamano = "Pequeño", Peso = "10-11 kg", Edad = "13-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/basenji-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Basset fauve de bretaña", Tamano = "Pequeño", Peso = "12-16 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/basset-fauve-de-bretagne-dog-breed-full-body.webp" },
                new Perro { Nombre = "Beagle", Tamano = "Pequeño", Peso = "9-14 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/beagle-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Beagle de bolsillo", Tamano = "Pequeño", Peso = "3-7 kg", Edad = "10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/pocket-beagle-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Beaglier", Tamano = "Pequeño", Peso = "5-9 kg", Edad = "10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/beaglier-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Bichón frisé", Tamano = "Pequeño", Peso = "5-8 kg", Edad = "14-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bichon-frise-dog-breed-full-body.webp" },
                new Perro { Nombre = "Bichón maltés ", Tamano = "Pequeño", Peso = "4-6 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/maltese-bichon-maltichon-dog-breed-full-body.webp" },
                new Perro { Nombre = "Biewer terrier", Tamano = "Pequeño", Peso = "2-4 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/biewer-terrier-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Boloñesa", Tamano = "Pequeño", Peso = "2,5-4 kg ", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bolognese-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Bolonka zwetna", Tamano = "Pequeño", Peso = "2-5 kg", Edad = "12-16 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bolonka-zwetna-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Boshih", Tamano = "Pequeño", Peso = "5-9 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/boshih-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Bugg", Tamano = "Pequeño", Peso = "7-11 kg", Edad = "10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bugg-dog-breed-full-body.webp" },
                new Perro { Nombre = "Buldog de la riviera", Tamano = "Pequeño", Peso = "9-16 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/riviera-bulldog-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Buldog francés", Tamano = "Pequeño", Peso = "7-13 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/french-bulldog-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Buldog francés atigrado", Tamano = "Pequeño", Peso = "7-13 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/french-bulldog-brindle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Bull terrier miniatura", Tamano = "Pequeño", Peso = "8-13 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/miniature-bull-terrier-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Bullhuahua francés", Tamano = "Pequeño", Peso = "5-14 kg", Edad = "10-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/french-bullhuahua-dog-breed-full-body.webp" },
                new Perro { Nombre = "Caniche", Tamano = "Pequeño", Peso = "1,8-41 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/poodle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Caniche francés", Tamano = "Pequeño", Peso = "3-32 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/french-poodle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Caniche miniatura", Tamano = "Pequeño", Peso = "4,5-8 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/miniature-poodle-caniche-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Caniche toy", Tamano = "Pequeño", Peso = "1,8-2,7 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/toy-poodle-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Cárdigan corgi galés", Tamano = "Pequeño", Peso = "11-17 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cardigan-welsh-corgi-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cav-a-jack", Tamano = "Pequeño", Peso = "6-8 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cav-a-jack-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cavachón", Tamano = "Pequeño", Peso = "7-16 kg", Edad = "10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavachon-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cavalier king charles spaniel", Tamano = "Pequeño", Peso = "6-8 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavalier-king-charles-spaniel-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cavapoo (Cavoodle)", Tamano = "Pequeño", Peso = "4-11 kg", Edad = " 12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavapoo-cavoodle-dog-breed-full-body-side-768x576.webp" },
                new Perro { Nombre = "Cavapoochon", Tamano = "Pequeño", Peso = "5-9 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavapoochon-dog-breed-full-body-side-768x576.jpg" },
                new Perro { Nombre = "Cavoodle", Tamano = "Pequeño", Peso = "4-11 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/cavapoo-cavoodle-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cesky Terrier", Tamano = "Pequeño", Peso = "6-11 kg ", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/cesky-terrier-czech-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Cheagle", Tamano = "Pequeño", Peso = "4-9 kg", Edad = "10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/cheagle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Chi-poo", Tamano = "Pequeño", Peso = "2-9 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/chi-poo-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Chigi", Tamano = "Pequeño", Peso = "5-9 kg", Edad = "12-16 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/chigi-dog-breed-full-body1-768x576.webp" },
                new Perro { Nombre = "Afador", Tamano = "Mediano", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/09/afador-dog-breed-full-body.webp" },
                new Perro { Nombre = "American Bully", Tamano = "Mediano", Peso = "32-54 kg", Edad = "8-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/american-bully-dog-breed-full-body.webp" },
                new Perro { Nombre = "Antiguo bulldog inglés", Tamano = "Mediano", Peso = "18-23 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/old-english-bulldog-dog-breed-full-body.webp" },
                new Perro { Nombre = "Árboles tennessee brindle", Tamano = "Mediano", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/treeing-tennessee-brindle-cur-dog-breed-full-body.webp" },
                new Perro { Nombre = "Ariegeois", Tamano = "Mediano", Peso = "25-27 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/ariegeois-dog-breed-full-body.webp" },
                new Perro { Nombre = "Askal", Tamano = "Mediano", Peso = "11-29 kg ", Edad = "10-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/askal-aspin-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Aso ng gubat", Tamano = "Mediano", Peso = "14-20 kg ", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/aso-ng-gubat-philippine-forest-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Auvergne Pointer", Tamano = "Mediano", Peso = "23-27 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/auvergne-pointer-braque-d-auvergne-dog-breed-full-body-side-view-768x576.webp" },
                new Perro { Nombre = "Azul de gascuña", Tamano = "Mediano", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/gascony-blue-bleu-de-gascogne-dog-breed-full-body.webp" },
                new Perro { Nombre = "Barak bosnio", Tamano = "Mediano", Peso = "16-25 kg ", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bosnian-barak-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Barbado da terceira", Tamano = "Mediano", Peso = "23-29 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/09/barbado-da-terceira-dog-breed-full-body.webp" },
                new Perro { Nombre = "Barbet", Tamano = "Mediano", Peso = "17-28 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/barbet-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Bardino majorero", Tamano = "Mediano", Peso = "25-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bardino-majorero-dog-breed-full-body-side-view.webp" },
                new Perro { Nombre = "Bassador", Tamano = "Mediano", Peso = "20-32 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bassador-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Basset artésien normando", Tamano = "Mediano", Peso = "15-20 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/basset-artesien-normand-dog-breed-full-body.webp" },
                new Perro { Nombre = "Basset azul de gascuña", Tamano = "Mediano", Peso = "16-18 kg", Edad = "10-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/blue-gascony-basset-dog-breed-full-body-1-768x576.webp" },
                new Perro { Nombre = "Basset hound", Tamano = "Mediano", Peso = "18-29 kg", Edad = "12-13 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/basset-hound-dog-breed-full-body.webp" },
                new Perro { Nombre = "Beabull", Tamano = "Mediano", Peso = "14-27 kg ", Edad = "10-13 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/beabull-dog-breed-full-body.webp" },
                new Perro { Nombre = "Beagle", Tamano = "Mediano", Peso = "9-14 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/beagle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Beaglier", Tamano = "Mediano", Peso = "5-9 kg", Edad = "10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/beaglier-dog-breed-full-body.webp" },
                new Perro { Nombre = "Berger picard", Tamano = "Mediano", Peso = "23-32 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/berger-picard-dog-breed-full-body.webp" },
                new Perro { Nombre = "Bernedoodle", Tamano = "Mediano", Peso = "32-41 kg ", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bernedoodle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Dalmador", Tamano = "Mediano", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/01/dalmador-dog-breed-full-body.webp" },
                new Perro { Nombre = "Dálmata", Tamano = "Mediano", Peso = "20-32 kg", Edad = "11-13 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/dalmatian-dog-breed-full-body.webp" },
                new Perro { Nombre = "Dingo", Tamano = "Mediano", Peso = "13-20 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/dingo-dog-breed-full-body.webp" },
                new Perro { Nombre = "Doodle australiano", Tamano = "Mediano", Peso = "18-32 kg ", Edad = " 10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/aussiedoodle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Drever", Tamano = "Mediano", Peso = "14-16 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/drever-dog-breed-full-body.webp" },
                new Perro { Nombre = "Eurasier", Tamano = "Mediano", Peso = "23-32 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/eurasier-dog-breed-full-body.webp" },
                new Perro { Nombre = "Frengle", Tamano = "Mediano", Peso = "8-14 kg", Edad = "10-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/frengle-dog-breed-full-body.webp" },
                new Perro { Nombre = "Galgo español", Tamano = "Mediano", Peso = "23-29 kg", Edad = "10-13 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/galgo-espanol-dog-breed-full-body.webp" },
                new Perro { Nombre = "Gollie", Tamano = "Mediano", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/gollie-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Hokkaido", Tamano = "Mediano", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/12/hokkaido-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Horgi", Tamano = "Mediano", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/01/horgi-dog-breed-full-body.webp" },
                new Perro { Nombre = "Husky siberiano", Tamano = "Mediano", Peso = "16-27 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/siberian-husky-dog-breed-full-body.webp" },
                new Perro { Nombre = "Karakachan", Tamano = "Grande", Peso = "40-50 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/karakachan-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Kombai", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/12/kombai-dog-breed-full-body.webp" },
                new Perro { Nombre = "Komondor", Tamano = "Grande", Peso = "36-45 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/komondor-dog-breed-full-body.webp" },
                new Perro { Nombre = "Kuvasz", Tamano = "Grande", Peso = "32-34 kg ", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/12/kuvasz-dog-breed-full-body.webp" },
                new Perro { Nombre = "Lab Pointer", Tamano = "Grande", Peso = "23-34 kg ", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/lab-pointer-dog-breed-full-body.webp" },
                new Perro { Nombre = "Labrabull", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/labrabull-dog-breed-full-body-1.webp" },
                new Perro { Nombre = "Labradano", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/labradane-dog-breed-full-body.webp" },
                new Perro { Nombre = "Labrador británico", Tamano = "Grande", Peso = "25-36 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/british-labrador-dog-breed-full-body.webp" },
                new Perro { Nombre = "Labrador chocolateado", Tamano = "Grande", Peso = "25-36 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/chocolate-labrador-dog-breed-full-body.webp" },
                new Perro { Nombre = "Labrador negro", Tamano = "Grande", Peso = "25-36 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/black-labrador-dog-breed-full-body.webp" },
                new Perro { Nombre = "Labrador plateado", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/silver-labrador-dog-breed-full-body.webp" },
                new Perro { Nombre = "Labrador zorro rojo", Tamano = "Grande", Peso = "25-36 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/red-fox-labrador-dog-breed-full-body.webp" },
                new Perro { Nombre = "Labsky", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/labsky-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Laika yakutiana", Tamano = "Grande", Peso = "23-34 kg ", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/12/yakutian-laika-dog-breed-full-body.webp" },
                new Perro { Nombre = "Lebrel Afgano", Tamano = "Grande", Peso = "23-27 kg", Edad = "12-15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/09/afghan-hound-dog-breed-full-body.webp" },
                new Perro { Nombre = "Lebrel escocés", Tamano = "Grande", Peso = "34-50 kg ",Edad = "8-11 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/scottish-deerhound-dog-breed-full-body-1024x768.webp" },
                new Perro { Nombre = "Lurcher", Tamano = "Grande", Peso = "23-34 kg ", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/12/lurcher-dog-breed-full-body.webp" },
                new Perro { Nombre = "Lykos Wolfalike", Tamano = "Grande", Peso = "30–40 kg", Edad = "10–15 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/lykos-wolfalike-dog-breed-full-body.webp" },
                new Perro { Nombre = "Mastador", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/mastador-dog-breed-full-body.webp" },
                new Perro { Nombre = "Mastín brasileño", Tamano = "Grande", Peso = "41-82 kg", Edad = "9-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/brazilian-mastiff-dog-breed-full-body.webp" },
                new Perro { Nombre = "Mastín napolitano", Tamano = "Grande", Peso = "50-68 kg ", Edad = "8-10 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/neapolitan-mastiff-dog-breed-full-body.webp" },
                new Perro { Nombre = "Newfoundland", Tamano = "Grande", Peso = "45-68 kg", Edad = "8-10 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/newfoundland-dog-breed-full-body.webp" },
                new Perro { Nombre = "Otterhound", Tamano = "Grande", Peso = "36-52 kg", Edad = "10-13 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/01/otterhound-dog-breed-full-body.webp" },
                new Perro { Nombre = "Pastor alemán", Tamano = "Grande", Peso = "23-34 kg ", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/01/german-sheprador-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Pastor chow", Tamano = "Grande", Peso = "20-41 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/chow-shepherd-dog-breed-full-body.webp" },
                new Perro { Nombre = "Pudelpointer", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/04/pudelpointer-dog-breed-full-body.webp" },
                new Perro { Nombre = "Pyredoodle", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/pyredoodle-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Rajapalayam", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/12/rajapalayam-dog-breed-full-body.webp" },
                new Perro { Nombre = "Ridgeback tailandés", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/thai-ridgeback-dog-breed-full-body.webp" },
                new Perro { Nombre = "Rotterman",Tamano = "Grande", Peso = "23-35 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/03/rotterman-dog-breed-full-body.webp" },
                new Perro { Nombre = "Rottweiler", Tamano = "Grande", Peso = "36-61 kg ", Edad = "8-10 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/rottweiler-dog-breed-full-body-768x576.webp" },
                new Perro { Nombre = "Sabueso", Tamano = "Grande", Peso = "23-34 kg", Edad = "10-12 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/12/staghound-dog-breed-full-body.webp" },
                new Perro { Nombre = "Saluki", Tamano = "Grande", Peso = "18-29 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/saluki-dog-breed-full-body.webp" },
                new Perro { Nombre = "Weimaraner", Tamano = "Grande", Peso = "25-41 kg", Edad = "10-13 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/weimaraner-dog-breed-full-body.webp" },
                new Perro { Nombre = "Shih tzu maltés", Tamano = "Pequeño", Peso = "3-5 kg", Edad = "12-14 años", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/maltese-shih-tzu-malshi-dog-breed-full-body-1536x1152.webp" }
            };

            return View(perros);
        }
        
    }
}
